// Generated by wxt
import "wxt/browser";

declare module "wxt/browser" {
  export type PublicPath =
    | ""
    | "/"
    | "/background.js"
    | "/blank.html"
    | "/content-scripts/userscript-bridge.js"
    | "/font/Cause-ExtraBold.ttf"
    | "/forgot-password.html"
    | "/icon/128.png"
    | "/icon/16.png"
    | "/icon/48.png"
    | "/offscreen.html"
    | "/popup.html"
    | "/userscripts/seswi-bridge-helper.user.js"
  type HtmlPublicPath = Extract<PublicPath, `${string}.html`>
  export interface WxtRuntime {
    getURL(path: PublicPath): string;
    getURL(path: `${HtmlPublicPath}${string}`): string;
  }
}
