/**
 * SesWi Export Module
 * Handles data formatting for exports (JSON, Netscape)
 */

export const Export = {
  /**
   * Convert cookies to formatted JSON string
   * @param {Array} cookies - Array of cookie objects
   * @returns {string} JSON string
   */
  toJSON(cookies) {
    return JSON.stringify(cookies, null, 2);
  },

  /**
   * Convert cookies to Netscape HTTP Cookie File format
   * Based on: https://github.com/osiro/netscape-cookies-exporter
   * @param {Array} cookies - Array of cookie objects
   * @returns {string} Netscape formatted string
   */
  toNetscape(cookies) {
    const header = [
      "# Netscape HTTP Cookie File",
      "# This was generated by SesWi (https://github.com/risunCode/SesWi-Session-Manager)",
      "# Do not edit.",
      ""
    ].join("\n");

    const rows = cookies
      .sort((a, b) => {
        const domainA = a.domain || '';
        const domainB = b.domain || '';
        return domainA.localeCompare(domainB);
      })
      .map(c => {
        // Netscape format: domain, include_subdomains, path, secure, expires, name, value
        // Domains usually start with dot in Netscape format
        const domain = c.domain.startsWith('.') ? c.domain : `.${c.domain}`;

        // Include subdomains - typically TRUE for all in this format unless strictly host-only
        const includeSubdomains = "TRUE";

        const path = c.path || '/';
        const secure = c.secure ? "TRUE" : "FALSE";

        // Expiration: seconds since epoch
        // If session cookie (no expirationDate), set to 0 or arbitrary future date?
        // Netscape format usually expects a timestamp. 0 often means session.
        // However, some importers might ignore 0.
        // Let's use 0 for session cookies as per spec, or 1 year if it causes issues.
        // But spec says: "The date string is a decimal number of seconds since Jan 1st 1970 GMT."
        // For session cookies, standard is 0.
        let expires = 0;
        if (c.expirationDate) {
          expires = Math.round(c.expirationDate);
        } else {
          // If strict Netscape format requires a date for persistence, but we want session behavior.
          // We'll stick to 0.
          expires = 0;
        }

        return [
          domain,
          includeSubdomains,
          path,
          secure,
          expires,
          c.name,
          c.value
        ].join("\t");
      });

    return header + "\n" + rows.join("\n");
  }
};
