import type { Cookie } from './session.types.js';

export const Export = {
  toJSON(cookies: Cookie[]): string {
    return JSON.stringify(cookies, null, 2);
  },
  toCookieEditor(cookies: Cookie[]): string {
    return JSON.stringify(cookies.map(cookie => ({
      domain: cookie.domain ?? '',
      expirationDate: cookie.expirationDate,
      hostOnly: !(cookie.domain ?? '').startsWith('.'),
      httpOnly: cookie.httpOnly ?? false,
      name: cookie.name,
      path: cookie.path ?? '/',
      sameSite: cookie.sameSite ?? 'unspecified',
      secure: cookie.secure ?? false,
      session: !cookie.expirationDate,
      storeId: cookie.storeId ?? '0',
      value: cookie.value ?? '',
    })), null, 2);
  },
  toNetscape(cookies: Cookie[]): string {
    const header = [
      '# Netscape HTTP Cookie File',
      '# This was generated by SesWi (https://github.com/risunCode/SesWi-Session-Manager)',
      '# Do not edit.',
      '',
    ].join('\n');
    const rows = [...cookies]
      .sort((a, b) => (a.domain ?? '').localeCompare(b.domain ?? ''))
      .map(cookie => [
        (cookie.domain ?? '').startsWith('.') ? cookie.domain ?? '' : `.${cookie.domain ?? ''}`,
        'TRUE',
        cookie.path ?? '/',
        cookie.secure ? 'TRUE' : 'FALSE',
        cookie.expirationDate ? Math.round(cookie.expirationDate) : 0,
        cookie.name,
        cookie.value,
      ].join('\t'));
    return `${header}\n${rows.join('\n')}`;
  },
} as const;
